author: Andrej Mihajlov
copyright: Copyright (c) 2013-present Andrej Mihajlov
author_url: http://codeispoetry.ru/
github_url: https://github.com/pronebird/UIScrollView-InfiniteScroll
github_file_prefix: https://github.com/pronebird/UIScrollView-InfiniteScroll/tree/9cddbf4d89

module: UIScrollView_InfiniteScroll
module_version: 1.3.0

clean: true
theme: fullwidth
objc: true
sdk: iphonesimulator

framework_root: Sources/UIScrollView_InfiniteScroll
umbrella_header: Sources/UIScrollView_InfiniteScroll/UIScrollView+InfiniteScroll.h
